name: Test CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        run: sudo apt-get install nodejs
      - name: Install AppCenter CLI
        run: sudo npm install -g appcenter-cli
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Keytool
        run: keytool -genkey -v -keystore app/my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-alias -keypass password -storepass password -dname "CN=mqttserver.ibm.com, OU=ID, O=IBM, L=Hursley, S=Hants, C=GB"  -noprompt
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Distribute
        run: appcenter distribute release --group CVS --file build/outputs/apk/debug/app-debug.apk --app CodingBook/CVS-Android --token ${{ secrets.APPCENTER }}  --quiet
